project_name: rcon-cli
before:
  hooks:
    - go mod download
release:
  github:
    owner: itzg
    name: rcon-cli
builds:
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  goarm:
  - 6
  - 7
  main: .
  binary: rcon-cli
  env:
    - CGO_ENABLED=0
archives:
  -
    format: tar.gz
    name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{
      .Arm }}{{ end }}'
    files:
    - licence*
    - LICENCE*
    - license*
    - LICENSE*
    - readme*
    - README*
    - changelog*
    - CHANGELOG*
changelog:
  filters:
    exclude:
      - '^ci:'
      - '^docs:'
dockers:
  - image_templates:
      - "itzg/rcon-cli:{{ .Version }}-amd64"
      - "itzg/rcon-cli:latest"
    binaries:
      - rcon-cli
    goos: linux
    goarch: amd64
  - image_templates:
      - "itzg/rcon-cli:{{ .Version }}-arm64"
    binaries:
      - rcon-cli
    goos: linux
    goarch: arm64
docker_manifests:
  - name_template: "itzg/rcon-cli:{{ .Version }}"
    image_templates:
      - "itzg/rcon-cli:{{ .Version }}-amd64"
      - "itzg/rcon-cli:{{ .Version }}-arm64"
scoop:
  bucket:
    owner: itzg
    name: scoop-bucket
  license: Apache2
  description: Enables REST-like access to HTML pages by scraping and parsing them into JSON
