version: 2
executorType: docker
containerInfo:
  - image: golang:1.8
    cmd: ["/bin/bash"]
stages:
  build:
    workDir: /go/src/github.com/itzg/rcon-cli
    steps:
      - type: checkout
      - type: shell
        command: |
          curl https://glide.sh/get | sh
          glide install
          go build
      - type: deploy
        command: |
          tag=$(git describe --exact-match --tags)
          if [ $? = 0 ]; then
            go get github.com/mitchellh/gox
            go get github.com/tcnksm/ghr
            CGO_ENABLED=0 gox \
              -output "dist/rcon-cli_{{.OS}}_{{.Arch}}"
            ghr -u $CIRCLE_USERNAME -r rcon-cli --replace $tag dist/
          else
            echo "Not tagged, so skipping deploy"
          fi