version: 2

defaults: &defaults
  docker:
    - image: circleci/golang:1.11

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - cache-{{ arch }}-{{ .Branch }}-{{ checksum "go.sum" }}
            - cache-{{ arch }}-{{ .Branch }}
            - cache

      - run: go mod download

      - save_cache:
          key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "go.sum" }}
          paths:
            - /go/pkg

      - run: go test -mod=readonly

  release:
    <<: *defaults
    steps:
      - checkout

      - setup_remote_docker
      - run:
          name: docker login
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: goreleaser
          command: curl -sL https://git.io/goreleaser | bash -s -- --skip-publish

workflows:
  version: 2
  main:
    jobs:
      - build

  release:
    jobs:
      - release:
          filters:
            tags:
              only: /\d+(\.\d+)*(-.*)*/
            branches:
              ignore: /.*/